AWSTemplateFormatVersion: '2010-09-09'
Resources:
  JokesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Jokes
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST